services:
  frontend:
    depends_on:
      - cms
    restart: unless-stopped
    image: hjcasayas/browse-everything-frontend:v1.2.0
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      tags:
        - hjcasayas/browse-everything-frontend:latest
        - hjcasayas/browse-everything-frontend:v1.2.0
      platforms:
        - linux/amd64
        - linux/arm64
  cms:
    depends_on:
      - db
    restart: unless-stopped
    image: hjcasayas/browse-everything-cms:v1.2.0
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
      tags:
        - hjcasayas/browse-everything-cms:latest
        - hjcasayas/browse-everything-cms:v1.2.0
      platforms:
        - linux/amd64
        - linux/arm64
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data
  cloudflare-fe:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./.env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_FE}
  cloudflare-cms:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./.env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_CMS}
volumes:
  prod-postgres-data:
